version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: airflow_postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"

  airflow-init:
    image: apache/airflow:2.7.3
    depends_on:
      - postgres
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    entrypoint: >
      bash -c "
        pip install pyspark &&
        airflow db init
      "
    volumes:
      - ./airflow:/opt/airflow

  airflow-webserver:
    image: apache/airflow:2.7.3
    container_name: airflow_webserver
    depends_on:
      - airflow-init
    restart: always
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    ports:
      - "8080:8080"
    entrypoint: >
      bash -c "
        pip install pyspark &&
        airflow webserver
      "
    volumes:
      - ./airflow:/opt/airflow

  airflow-scheduler:
    image: apache/airflow:2.7.3
    container_name: airflow_scheduler
    depends_on:
      - airflow-webserver
    restart: always
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    entrypoint: >
      bash -c "
        pip install pyspark &&
        airflow scheduler
      "
    volumes:
      - ./airflow:/opt/airflow
